# Appveyor continuous builder configuration

# Version format, we don't have version number for ADL yet
version: 0.0.{build}

# Setup python for build and test-suite scripts
environment:
  PYTHON: C:\\Python27
  TOOLS_DIR: C:\ADL_tools\
  GNAT_NATIVE_INSTALLER: C:\ADL_tools\gnat-community-2018-x86_64-windows-bin.exe
  GNAT_ARM_ELF_INSTALLER: C:\ADL_tools\gnat-community-2018-arm-elf-windows-bin.exe
  INSTALL_DIR: C:\Install\
  INSTALL_CONTROL_SCRIPT: C:\projects\ada-drivers-library\scripts\GNAT_CE_2018_install_control.qs

# Cache directories will be preseved from one build to the other
cache:
  - C:\ADL_tools

on_failure:
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

install:
# Show current dir and its content
- cmd: cd
- cmd: dir

# Create the tool dir if it doesn't exists
- ps: md -f $env:TOOLS_DIR
- ps: md -f $env:INSTALL_DIR

# Show content of tool dir
- cmd: dir %TOOLS_DIR%
- cmd: dir %INSTALL_DIR%

# Download compiler installer if not already in the tool dir
- ps: If (Test-Path $env:GNAT_NATIVE_INSTALLER){echo compiler already in cache}Else{(new-object net.webclient).DownloadFile('http://mirrors.cdn.adacore.com/art/5b30f4e6c7a4477116360355', $env:GNAT_NATIVE_INSTALLER)}
- ps: If (Test-Path $env:GNAT_ARM_ELF_INSTALLER){echo compiler already in cache}Else{(new-object net.webclient).DownloadFile('http://mirrors.cdn.adacore.com/art/5b0843e7a3f5d75c215f46b6', $env:GNAT_ARM_ELF_INSTALLER)}

# Show content of tool dir again so we can see if the download was ok
- cmd: dir %TOOLS_DIR%

- ps: Invoke-WebRequest https://raw.githubusercontent.com/AdaCore/gnat_community_install_script/master/install_package.bat -OutFile install_package.bat
- ps: Invoke-WebRequest https://raw.githubusercontent.com/AdaCore/gnat_community_install_script/master/install_script.qs -OutFile install_script.qs

# Install the compilers
- cmd: install_package.bat %GNAT_NATIVE_INSTALLER% C:\Install\native
- cmd: install_package.bat %GNAT_ARM_ELF_INSTALLER% C:\Install\arm-elf

# Show content of install dir so we can see if install was ok
- cmd: dir %INSTALL_DIR%
- cmd: dir C:\Install\

# Add compiler to the PATH
- ps: $env:Path += ";" + $env:INSTALL_DIR +"\native\bin"
- ps: $env:Path += ";" + $env:INSTALL_DIR +"\arm-elf\bin"

# Check that we can run the compiler (also display the version)
- ps: arm-eabi-gnatls -v

# Install optional dependencies
- cmd: python scripts/install_dependencies.py

# We don't need a build step
build: off

# Run the test scripts
test_script:
- cmd: python scripts/build_all_examples.py
- cmd: python testsuite/run.py
